from __future__ import annotations

from . import db

_SEED_DOCS = {
    "Business Management": (
        "Management is the process of planning, organizing, leading, and controlling "
        "organizational resources to achieve goals efficiently and effectively. "
        "Key management functions include strategic planning (setting long-term direction and objectives), "
        "organizational design (structuring teams and departments), leadership and motivation, "
        "performance management, and quality control. "
        "Modern management theories include Transformational Leadership, which inspires teams through vision, "
        "Situational Leadership, which adapts style to follower maturity, "
        "and Agile Management, which emphasizes iterative delivery, cross-functional teams, and continuous improvement. "
        "Decision-making frameworks like SWOT Analysis (Strengths, Weaknesses, Opportunities, Threats), "
        "the Eisenhower Matrix for prioritization, and OKRs (Objectives and Key Results) for goal setting "
        "are widely used. Effective managers practice delegation, provide regular feedback, "
        "and foster psychological safety. "
        "In the African context, Ubuntu management philosophy emphasizes community, collective decision-making, "
        "and shared leadership. African SMEs benefit from flat organizational structures "
        "that enable rapid decision-making and close customer relationships. "
        "Resource constraints require lean management practices—minimizing waste while maximizing value delivery. "
        "Key performance indicators (KPIs) for managers include employee productivity, retention rates, "
        "project completion rates, and team satisfaction scores."
    ),
    "Marketing": (
        "Marketing encompasses all activities that create, communicate, deliver, and exchange offerings "
        "that have value for customers, clients, partners, and society. "
        "The marketing mix (4Ps) framework comprises Product (features, quality, branding), "
        "Price (pricing strategy, discounts, payment terms), "
        "Place (distribution channels, market coverage, logistics), "
        "and Promotion (advertising, PR, sales promotion, digital marketing). "
        "Modern marketing has expanded to 7Ps—adding People (customer-facing staff), "
        "Process (service delivery workflows), and Physical Evidence (tangibles that signal quality). "
        "Digital marketing channels include SEO (search engine optimization), "
        "SEM (search engine marketing/PPC), social media marketing (Facebook, Instagram, LinkedIn, TikTok), "
        "email marketing, content marketing (blogs, videos, podcasts), and influencer marketing. "
        "Customer acquisition cost (CAC), lifetime value (LTV), conversion rate, and return on ad spend (ROAS) "
        "are critical metrics. "
        "Market research methods include surveys, focus groups, interviews, and A/B testing. "
        "Segmentation, Targeting, Positioning (STP) strategy helps businesses identify and serve specific market segments. "
        "In African markets, mobile-first marketing is essential—smartphone penetration exceeds 50% in most countries. "
        "USSD codes, WhatsApp Business, and mobile money platforms like M-Pesa are key distribution and payment channels. "
        "Trust is a major factor; word-of-mouth and community endorsements often outperform traditional advertising. "
        "Localization of messaging, pricing to local purchasing power, "
        "and leveraging informal trade networks are critical for market penetration."
    ),
    "Finance": (
        "Finance is the art and science of managing money. "
        "Key financial statements include the Income Statement (revenue, COGS, operating expenses, net profit), "
        "Balance Sheet (assets = liabilities + equity), and Cash Flow Statement (operating, investing, financing activities). "
        "Financial ratios are essential for analysis: Gross Margin = (Revenue - COGS) / Revenue, "
        "Net Profit Margin = Net Profit / Revenue, Current Ratio = Current Assets / Current Liabilities, "
        "and Debt-to-Equity = Total Liabilities / Shareholders' Equity. "
        "Budgeting involves forecasting revenue and expenses, allocating resources, "
        "and tracking variance between actual and planned figures. "
        "Cash flow management is critical for SMEs—monitoring receivables, payables, and inventory cycles "
        "to avoid liquidity crises. "
        "Investment analysis uses NPV (Net Present Value), IRR (Internal Rate of Return), "
        "and payback period to evaluate projects. "
        "In African business contexts, financial management must account for currency volatility, "
        "high inflation rates in some economies, diverse tax regimes across countries, "
        "and limited access to traditional banking. "
        "Mobile money platforms (M-Pesa, Airtel Money, Orange Money) are critical payment infrastructure. "
        "African SMEs often use informal savings mechanisms like tontines/esusu (rotating savings groups). "
        "Key financial challenges for African businesses include high interest rates (often 15-30%), "
        "collateral requirements for loans, lengthy payment cycles from government and large corporate clients, "
        "and multiple tax jurisdictions for cross-border trade. "
        "The African Continental Free Trade Area (AfCFTA) is creating new opportunities "
        "for pan-African trade and investment."
    ),
    "Business Law": (
        "Business law governs the formation, operation, and dissolution of businesses. "
        "Key business structures include Sole Proprietorship (full owner control, unlimited liability), "
        "Partnership (shared ownership, joint liability), "
        "Limited Liability Company (LLC) (separate legal entity, limited liability), "
        "and Corporation (shareholder-owned, complex governance). "
        "Company registration typically requires a business name, memorandum of association, "
        "articles of incorporation, and registration with the corporate affairs commission. "
        "Contract law essentials: offer, acceptance, consideration, capacity, and legality. "
        "Written contracts should clearly specify parties, scope of work, payment terms, delivery timelines, "
        "warranties, liability limits, termination clauses, and dispute resolution mechanisms. "
        "Intellectual property protection includes trademarks (brand names, logos), "
        "patents (inventions, processes), copyrights (creative works), and trade secrets. "
        "Employment law covers hiring contracts, minimum wage, working hours, leave entitlements, "
        "workplace safety, non-discrimination, and termination procedures. "
        "Tax compliance requires registration for VAT, corporate income tax, PAYE (pay-as-you-earn), "
        "and industry-specific levies. "
        "In African jurisdictions, common legal frameworks include OHADA (Organization for the Harmonization of Business Law in Africa) "
        "used by 17 West and Central African countries, "
        "and national company acts based on English common law or French civil law traditions. "
        "African SMEs should be aware of local content requirements, foreign ownership restrictions, "
        "and sector-specific regulations (e.g., fintech licenses from central banks, "
        "telecommunications permits from communications authorities). "
        "Dispute resolution options include litigation (court system), "
        "arbitration (binding, private), and mediation (non-binding, facilitated negotiation). "
        "Many African countries have specialized commercial courts or fast-track procedures for business disputes."
    ),
    "Business Politics": (
        "Business politics refers to the informal power dynamics, relationships, "
        "and influence structures within and around organizations. "
        "Stakeholder management involves identifying all parties affected by business decisions—"
        "employees, customers, suppliers, investors, regulators, communities—"
        "and balancing their often-competing interests. "
        "Corporate governance frameworks define how companies are directed and controlled. "
        "Key principles include accountability, transparency, fairness, and responsibility. "
        "Board composition, executive compensation, shareholder rights, and audit committees "
        "are core governance mechanisms. "
        "Negotiation strategies for business include distributive bargaining (fixed pie, win-lose), "
        "integrative negotiation (expanding the pie, win-win), "
        "and principled negotiation (focus on interests, not positions). "
        "BATNA (Best Alternative To a Negotiated Agreement) is a critical concept—knowing your walk-away option. "
        "Public relations (PR) manages the flow of information between an organization and the public. "
        "Crisis communication plans should be prepared for scenarios like product recalls, data breaches, "
        "and negative media coverage. "
        "Business ethics involves making decisions that balance profit with social responsibility. "
        "Ethical frameworks include utilitarianism (greatest good for the greatest number), "
        "deontology (duty-based rules), and virtue ethics (character-based). "
        "Corporate Social Responsibility (CSR) encompasses environmental sustainability, "
        "community investment, ethical labor practices, and transparent governance. "
        "In African business contexts, relationship-building is paramount—trust is earned through "
        "face-to-face meetings, community involvement, and demonstrated commitment. "
        "Understanding local power structures, traditional leadership (chiefs, elders), "
        "and political connections is important for market entry and operations. "
        "Corruption risks exist in many African markets; robust compliance programs, "
        "transparent procurement, and adherence to anti-bribery laws (like the UK Bribery Act and US FCPA) "
        "are essential for international businesses. "
        "The concept of 'African solutions to African problems' emphasizes locally-led development, "
        "respect for sovereignty, and partnerships based on mutual benefit rather than aid dependency. "
        "Effective business politics in Africa requires cultural intelligence—understanding "
        "communication styles (high-context vs low-context), time orientation, "
        "hierarchical vs egalitarian norms, and the role of extended family and community in business decisions."
    ),
    "Human Resources Management": (
        "Human Resources Management (HRM) is the strategic approach to managing an organization's "
        "most valuable asset—its people. HRM encompasses the entire employee lifecycle: "
        "recruitment and selection, onboarding, training and development, performance management, "
        "compensation and benefits, employee relations, and offboarding. "
        "Recruitment involves job analysis, writing job descriptions, sourcing candidates (internal and external), "
        "screening resumes, conducting interviews (structured, behavioral, panel), "
        "administering assessments, checking references, and extending offers. "
        "Common recruitment channels include job boards, LinkedIn, recruitment agencies, campus hiring, "
        "employee referrals, and social media. "
        "Performance management includes setting KPIs and OKRs, conducting regular performance reviews, "
        "providing feedback, managing underperformance, and recognizing high performers. "
        "Training and development covers onboarding/orientation, skills training, leadership development, "
        "mentorship programs, and continuing professional education. "
        "Compensation management involves salary benchmarking, designing pay structures, "
        "bonus and incentive schemes, benefits administration (health insurance, pensions, leave), "
        "and ensuring pay equity. "
        "Employee relations addresses workplace conflict resolution, disciplinary procedures, "
        "grievance handling, union relations, and fostering a positive organizational culture. "
        "HR metrics include time-to-hire, cost-per-hire, turnover rate, retention rate, "
        "employee engagement score, absenteeism rate, and training ROI. "
        "Employment laws govern minimum wage, working hours, overtime, leave entitlements, "
        "health and safety, non-discrimination, and termination procedures. "
        "In the African context, HR practices must account for diverse labor laws across countries, "
        "cultural attitudes toward hierarchy and authority, the role of extended family in employee obligations, "
        "high youth unemployment requiring apprenticeship and internship programs, "
        "and the growing gig economy and remote work trends. "
        "Key African labor laws include Nigeria's Labour Act, Kenya's Employment Act, "
        "South Africa's Basic Conditions of Employment Act and Employment Equity Act, "
        "and Ghana's Labour Act 2003. "
        "HR challenges in Africa include skills shortages in specialized fields, "
        "brain drain to developed countries, informal sector employment (over 80% in some economies), "
        "and managing diverse workforces across multiple language and cultural groups. "
        "Strategic HRM practices like workforce planning, talent management, succession planning, "
        "and employer branding are increasingly adopted by African organizations "
        "to compete for talent in a globalized market."
    ),
}


def seed_knowledge_base():
    existing = db.list_documents()
    seeded_names = {d["doc_name"] for d in existing}
    added = 0
    for doc_name, text in _SEED_DOCS.items():
        if doc_name not in seeded_names:
            result = db.add_document(doc_name, text)
            added += 1
    return added
